name: tumlive
channels:
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - aom=3.12.1
  - attrs=25.4.0
  - backports-datetime-fromisoformat=2.0.3
  - beautifulsoup4=4.14.2
  - blinker=1.9.0
  - brotlicffi=1.2.0.0
  - bzip2=1.0.8
  - ca-certificates=2025.12.2
  - cairo=1.18.4
  - certifi=2026.01.04
  - cffi=2.0.0
  - charset-normalizer=3.4.4
  - click=8.2.1
  - dav1d=1.2.1
  - expat=2.7.1
  - ffmpeg=6.1.1
  - flask=3.1.2
  - flask_cors=3.0.10
  - fontconfig=2.15.0
  - freetype=2.13.3
  - fribidi=1.0.10
  - gdk-pixbuf=2.42.10
  - gettext=0.21.0
  - giflib=5.2.2
  - glib=2.84.4
  - glib-tools=2.84.4
  - graphite2=1.3.14
  - h11=0.16.0
  - harfbuzz=10.4.0
  - icu=75.1
  - idna=3.11
  - itsdangerous=2.2.0
  - jinja2=3.1.6
  - jpeg=9f
  - lame=3.100
  - lcms2=2.16
  - leptonica=1.82.0
  - lerc=4.0.0
  - libarchive=3.8.2
  - libcxx=20.1.8
  - libdeflate=1.22
  - libexpat=2.7.1
  - libffi=3.5.2
  - libglib=2.84.4
  - libiconv=1.18
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libmpdec=4.0.0
  - libogg=1.3.5
  - libopenjpeg=2.5.4
  - libopus=1.3.1
  - libpng=1.6.50
  - librsvg=2.56.3
  - libsqlite=3.50.4
  - libtheora=1.2.0
  - libtiff=4.7.0
  - libuv=1.51.0
  - libvorbis=1.3.7
  - libvpx=1.13.1
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxml2=2.13.9
  - libzlib=1.3.1
  - llvm-openmp=20.1.8
  - lz4-c=1.9.4
  - m3u8=6.0.0
  - markupsafe=3.0.2
  - ncurses=6.5
  - nodejs=24.4.1
  - openh264=2.6.0
  - openjpeg=2.5.4
  - openssl=3.5.4
  - outcome=1.3.0
  - pango=1.50.7
  - pcre2=10.46
  - pip=25.2
  - pixman=0.46.4
  - psutil=7.0.0
  - pycparser=2.23
  - pysocks=1.7.1
  - python=3.13.9
  - python_abi=3.13
  - pyyaml=6.0.3
  - readline=8.2
  - requests=2.32.5
  - selenium=4.38.0
  - setuptools=80.9.0
  - six=1.17.0
  - sniffio=1.3.1
  - sortedcontainers=2.4.0
  - soupsieve=2.5
  - tesseract=5.2.0
  - tk=8.6.13
  - tqdm=4.67.1
  - trio=0.32.0
  - trio-websocket=0.12.2
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - tzdata=2025b
  - urllib3=2.6.3
  - websocket-client=1.8.0
  - werkzeug=3.1.3
  - wheel=0.45.1
  - wsproto=1.3.1
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - yaml=0.2.5
  - zlib=1.3.1
  - zstd=1.5.7
prefix: /Users/pooya/miniconda3/envs/tumlive
