name: tumlive
channels:
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - aom=3.12.1
  - bzip2=1.0.8
  - ca-certificates=2025.11.4
  - cairo=1.18.4
  - dav1d=1.2.1
  - expat=2.7.1
  - ffmpeg=6.1.1
  - fontconfig=2.15.0
  - freetype=2.13.3
  - fribidi=1.0.10
  - gdk-pixbuf=2.42.10
  - gettext=0.21.0
  - giflib=5.2.2
  - glib=2.84.4
  - glib-tools=2.84.4
  - graphite2=1.3.14
  - harfbuzz=10.4.0
  - icu=75.1
  - jpeg=9f
  - lame=3.100
  - lcms2=2.16
  - leptonica=1.82.0
  - lerc=4.0.0
  - libarchive=3.8.2
  - libcxx=20.1.8
  - libdeflate=1.22
  - libexpat=2.7.1
  - libffi=3.5.2
  - libglib=2.84.4
  - libiconv=1.18
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libmpdec=4.0.0
  - libogg=1.3.5
  - libopenjpeg=2.5.4
  - libopus=1.3.1
  - libpng=1.6.50
  - librsvg=2.56.3
  - libsqlite=3.50.4
  - libtheora=1.2.0
  - libtiff=4.7.0
  - libuv=1.51.0
  - libvorbis=1.3.7
  - libvpx=1.13.1
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxml2=2.13.9
  - libzlib=1.3.1
  - llvm-openmp=20.1.8
  - lz4-c=1.9.4
  - ncurses=6.5
  - nodejs=24.4.1
  - openh264=2.6.0
  - openjpeg=2.5.4
  - openssl=3.5.4
  - pango=1.50.7
  - pcre2=10.46
  - pip=25.2
  - pixman=0.46.4
  - python=3.13.9
  - python_abi=3.13
  - readline=8.2
  - tesseract=5.2.0
  - tk=8.6.13
  - tqdm=4.67.1
  - tzdata=2025b
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - anyio==4.12.0
      - asyncio==4.0.0
      - attrs==25.4.0
      - auto-editor==27.1.1
      - basswood-av==15.2.1
      - beautifulsoup4==4.13.4
      - blinker==1.9.0
      - certifi==2025.10.5
      - charset-normalizer==3.4.4
      - click==8.3.1
      - dnspython==2.8.0
      - email-validator==2.3.0
      - execnet==2.1.1
      - fastapi==0.123.5
      - filelock==3.20.0
      - flask==3.0.0
      - flask-cors==4.0.0
      - frozenlist==1.8.0
      - h11==0.16.0
      - httpcore==1.0.9
      - httptools==0.7.1
      - httpx==0.28.1
      - idna==3.11
      - iniconfig==2.3.0
      - itsdangerous==2.2.0
      - jinja2==3.1.6
      - m3u8==6.0.0
      - markupsafe==3.0.3
      - multidict==6.7.0
      - numpy==2.3.4
      - outcome==1.3.0.post0
      - packaging==25.0
      - pluggy==1.6.0
      - propcache==0.4.1
      - psutil==7.1.3
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pysocks==1.7.1
      - pytest==8.3.5
      - pytest-rerunfailures==15.1
      - pytest-xdist==3.6.1
      - python-dotenv==1.2.1
      - pyyaml==6.0.1
      - requests==2.32.4
      - requests-file==3.0.1
      - selenium==4.15.0
      - selenium-requests==2.0.4
      - sniffio==1.3.1
      - sortedcontainers==2.4.0
      - soupsieve==2.8
      - starlette==0.50.0
      - tldextract==3.5.0
      - trio==0.32.0
      - trio-websocket==0.12.2
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - urllib3==2.5.0
      - uvicorn==0.38.0
      - uvloop==0.22.1
      - watchfiles==1.1.1
      - websocket-client==1.9.0
      - websockets==15.0.1
      - werkzeug==3.1.4
      - wsproto==1.2.0
      - yarl==1.22.0
prefix: /Users/pooya/miniconda3/envs/tumlive
