#TUM-live:
 # "ML": "https://live.rbg.tum.de/?year=2025&term=W&slug=WiSe25_26_ML&view=3"
 # "IDL": "https://live.rbg.tum.de/?year=2025&term=W&slug=WiSe25_26_ItDL&view=3"
#
Username: "go42tum"
Password: "hunter2"

Output-Folder: "/output"

Maximum-Parallel-Downloads: 3
