name: dev
channels:
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - aom=3.12.1=ha237518_0
  - bzip2=1.0.8=hd037594_8
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - cairo=1.18.4=h191e429_0
  - dav1d=1.2.1=h80987f9_0
  - expat=2.7.1=h313beb8_0
  - ffmpeg=6.1.1=h191590f_4
  - fontconfig=2.15.0=h29935d0_0
  - freetype=2.13.3=h47d26ad_0
  - fribidi=1.0.10=h1a28f6b_0
  - gdk-pixbuf=2.42.10=h969f7ef_2
  - gettext=0.21.0=hbdbcc25_2
  - giflib=5.2.2=h80987f9_0
  - glib=2.84.4=h863a760_0
  - glib-tools=2.84.4=hff4a405_0
  - graphite2=1.3.14=hc377ac9_1
  - harfbuzz=10.4.0=hb72c1af_0
  - icu=75.1=hfee45f7_0
  - jpeg=9f=h2f69dba_0
  - lame=3.100=h1a28f6b_0
  - lcms2=2.16=he26ebf3_1
  - leptonica=1.82.0=hdedf53e_3
  - lerc=4.0.0=h313beb8_0
  - libarchive=3.8.2=ha845c4f_0
  - libcxx=20.1.8=hd7fd590_1
  - libdeflate=1.22=h80987f9_0
  - libexpat=2.7.1=hec049ff_0
  - libffi=3.5.2=he5f378a_0
  - libglib=2.84.4=h7a3292d_0
  - libiconv=1.18=h23cfdf5_2
  - liblzma=5.8.1=h39f12f2_2
  - liblzma-devel=5.8.1=h39f12f2_2
  - libmpdec=4.0.0=h5505292_0
  - libogg=1.3.5=h1a28f6b_1
  - libopenjpeg=2.5.4=haa24f5a_1
  - libopus=1.3.1=h80987f9_1
  - libpng=1.6.50=h5c318fc_0
  - librsvg=2.56.3=h38920c8_2
  - libsqlite=3.50.4=h4237e3c_0
  - libtheora=1.2.0=h7de75a5_1
  - libtiff=4.7.0=h91aec0a_0
  - libvorbis=1.3.7=h1a28f6b_0
  - libvpx=1.13.1=h313beb8_0
  - libwebp=1.3.2=hf40cdb4_1
  - libwebp-base=1.3.2=h80987f9_1
  - libxml2=2.13.9=h4a9ca0c_0
  - libzlib=1.3.1=h8359307_2
  - llvm-openmp=20.1.8=he822017_0
  - lz4-c=1.9.4=h313beb8_1
  - ncurses=6.5=h5e97a16_3
  - openh264=2.6.0=h514c7bf_0
  - openjpeg=2.5.4=h959fc53_1
  - openssl=3.5.4=h5503f6c_0
  - pango=1.50.7=hf2328af_2
  - pcre2=10.46=h1dacb4a_0
  - pip=25.2=pyh145f28c_0
  - pixman=0.46.4=h09dc60e_0
  - python=3.13.9=hfc2f54d_101_cp313
  - python_abi=3.13=8_cp313
  - readline=8.2=h1d1bf99_2
  - tesseract=5.2.0=h9e66425_3
  - tk=8.6.13=h892fb3f_2
  - tqdm=4.67.1=py313h7eb115d_0
  - tzdata=2025b=h78e105d_0
  - xz=5.8.1=h9a6d368_2
  - xz-gpl-tools=5.8.1=h9a6d368_2
  - xz-tools=5.8.1=h39f12f2_2
  - zlib=1.3.1=h8359307_2
  - zstd=1.5.7=h817c040_0
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - asyncio==4.0.0
      - attrs==25.4.0
      - auto-editor==27.1.1
      - basswood-av==15.2.1
      - beautifulsoup4==4.13.4
      - certifi==2025.10.5
      - charset-normalizer==3.4.4
      - execnet==2.1.1
      - filelock==3.20.0
      - frozenlist==1.8.0
      - h11==0.16.0
      - idna==3.11
      - iniconfig==2.3.0
      - m3u8==6.0.0
      - multidict==6.7.0
      - numpy==2.3.4
      - outcome==1.3.0.post0
      - packaging==25.0
      - pluggy==1.6.0
      - propcache==0.4.1
      - pysocks==1.7.1
      - pytest==8.3.5
      - pytest-rerunfailures==15.1
      - pytest-xdist==3.6.1
      - pyyaml==6.0.2
      - requests==2.32.4
      - requests-file==3.0.1
      - selenium==4.32.0
      - selenium-requests==2.0.4
      - sniffio==1.3.1
      - sortedcontainers==2.4.0
      - soupsieve==2.8
      - tldextract==3.5.0
      - trio==0.32.0
      - trio-websocket==0.12.2
      - typing-extensions==4.15.0
      - urllib3==2.5.0
      - websocket-client==1.9.0
      - wsproto==1.2.0
      - yarl==1.22.0
